from enum import Enum


class ErrorStatus(str, Enum):
    NOT_FOUND = "NOT_FOUND"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    INTERNAL = "INTERNAL"
    ALREADY_EXISTS = "ALREADY_EXISTS"
